### ISSUE TITLE
Roadmap for the first release

### ISSUE THREAD

**Issue by Teufelchen1** [Teufelchen1/rv#9]
- [x] Add a README.md
- [x] Memory-mapped peripherals
    - [x] Basic idea
    - [x] Refine it & test via TUI I/O
    - [x] Comply UART with real hardware fe310
- [x] Working in- & output
    - [x] Input from shell
    - [x] Output to shell
    - [x] Input from TUI
    - [x] Output to TUI
- [x] Have a good and helpful module comment in each file
- [x] Have a logo & name (maybe @einhornwolle can help with that?)
- [x] The current instruction log of the TUI is confusing, fix that!
- [x] Loading of ELF files is very basic.
    - [x] No `unwrap`s
    - [x] Remove bad-ux `--file` argument
    - [x] Provide a way to load `bin` files

**Comment by Teufelchen1** [comment]
While it is very tempting to go ahead and add new RISC-V features, like User-Mode, CSR, PMP, C/PLIC, etc. if I want this project to become anything more than my personal toy, I *must* prioritize UX/UI and ensure a maintainable code base.
